// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwj8Ze_1rCkJcuncAjzTy6VlmT1zcwxW8',
    appId: '1:128731869307:web:e8d91dfccb127505af72de',
    messagingSenderId: '128731869307',
    projectId: 'virtualstudyroom-cfc3a',
    authDomain: 'virtualstudyroom-cfc3a.firebaseapp.com',
    storageBucket: 'virtualstudyroom-cfc3a.firebasestorage.app',
    measurementId: 'G-X6JZQ1CGC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWZfWDf4W35eKPo-Y2j2Zedl9-KIwi7O8',
    appId: '1:128731869307:android:2665dc93504987f2af72de',
    messagingSenderId: '128731869307',
    projectId: 'virtualstudyroom-cfc3a',
    storageBucket: 'virtualstudyroom-cfc3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmazJtdoQ4KgDFuGa1QgsZipKmlx-M-pA',
    appId: '1:128731869307:ios:4f296017c54a6026af72de',
    messagingSenderId: '128731869307',
    projectId: 'virtualstudyroom-cfc3a',
    storageBucket: 'virtualstudyroom-cfc3a.firebasestorage.app',
    iosBundleId: 'com.example.demoflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmazJtdoQ4KgDFuGa1QgsZipKmlx-M-pA',
    appId: '1:128731869307:ios:4f296017c54a6026af72de',
    messagingSenderId: '128731869307',
    projectId: 'virtualstudyroom-cfc3a',
    storageBucket: 'virtualstudyroom-cfc3a.firebasestorage.app',
    iosBundleId: 'com.example.demoflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwj8Ze_1rCkJcuncAjzTy6VlmT1zcwxW8',
    appId: '1:128731869307:web:dddacbf194ddb051af72de',
    messagingSenderId: '128731869307',
    projectId: 'virtualstudyroom-cfc3a',
    authDomain: 'virtualstudyroom-cfc3a.firebaseapp.com',
    storageBucket: 'virtualstudyroom-cfc3a.firebasestorage.app',
    measurementId: 'G-E25C6RYZ5T',
  );
}
